CREATE TABLE mobile (
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
modele VARCHAR(250) NOT NULL, 
marque VARCHAR(250) NOT NULL,
ram_go INT NOT NULL,
stockage_go INT NOT NULL,
etat VARCHAR(50) NOT NULL,
aspect VARCHAR(50) NOT NULL,
couleur VARCHAR(50) DEFAULT NULL,
taille_p INT DEFAULT NULL,
reseau VARCHAR(3) NOT NULL,
vendu BOOLEAN DEFAULT 0,
ville VARCHAR(250) NOT NULL,
date_entree DATE NOT NULL,
annee_prod DATE NOT NULL,
image VARCHAR(250) DEFAULT NULL,
ecouteurs BOOLEAN DEFAULT 0,
double_sim BOOLEAN DEFAULT 0,
commentaire TEXT DEFAULT NULL,
prix INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `user` (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
email VARCHAR(255) NOT NULL,
hashedPassword VARCHAR(255) NOT NULL,
admin BOOLEAN DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
